backend:
  name: git-gateway
  branch: main

media_folder: "assets/img/products"
public_folder: "/assets/img/products"

collections:
  - name: "products"
    label: "Products"
    folder: "data/products"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "name", widget: "string" }
      - { label: "Price (INR)", name: "price", widget: "number" }
      - { label: "Product Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Mark as New", name: "is_new", widget: "boolean", default: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
